server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/users/**

            - id: appointments-service
              uri: http://appointments-service:8082
              predicates:
                - Path=/api/appointments/**

